### PR TITLE
HMRC logo addition and test changes

### PR DESCRIPTION
**Pull request by scott-goodwin**

### CODE REVIEW

**Comment by etheya** [comment]
hi there Scott... the logo for HMRC should NOT be on the service, this was something passed down from GDS a long time ago, and it also interferes with the service on a mobile device. Please remove this back from the service ASAP.

**Comment by etheya** [comment]
Please DONT add this to the live service.

**Comment by etheya** [comment]
Services are NOT required to carry the HMRC logo and shouldnt do UNLESS the user clearly does not understand where they are or there is a clear reason to state the particular government department.

**Comment by scott-goodwin** [comment]
Good Morning Brian, 
Thank you for the quick comments and catching this before it went live. Speaking with the my lead Dev is there any chance you can forward on the links to the GDS information for this so that we have it on record or someone we can speak to. So if the team changes we have it on record.
Cheers Scott

**Comment by etheya** [comment]
Hi Scott, i will try and dig this out, it was a good few years ago that this was cascaded down. Also it impacts the services use on a mobile device as the logo takes up so much space in the header. Will see what i can find and attach to this ticket.

**Comment by etheya** [comment]
This is the current pattern link about it..

http://hmrc.github.io/assets-frontend/patterns/header/index.html

**Pull request closed without merging**
